const days=[
{date:"11/19",title:"台灣 → 關西 → 京都",sub:"出發・抵達京都・晚上自由活動",hotel:"Comfort Hotel Kyoto Horikawagojo",events:[["03:40","NOAH 新竹市出發"],["04:00","1250 客運 → 桃園機場 T1"],["05:00","T1 全員集合"],["07:40","JX820 → KIX"],["11:10","抵達 KIX"],["12:30","包車 → 京都飯店"],["15:00","飯店寄放／入住・休息"],["16:00","OPTION｜寺町・新京極・四条河原町"],["18:30","沿途晚餐"]]},
{date:"11/20",title:"和服・清水寺・祇園",sub:"本次主要人像攝影日",hotel:"Comfort Hotel Kyoto Horikawagojo",events:[["09:00","和服店｜3位女生著裝・髮型"],["10:00","清水寺"],["11:15","三年坂・二年坂"],["12:30","沿途午餐"],["14:00","八坂塔・高台寺方向"],["16:00","祇園・花見小路"],["17:15","歸還和服 → 河原町晚餐"]]},
{date:"11/21",title:"弘法市・糺之森・伏見稻荷",sub:"包車固定行程",hotel:"Comfort Hotel Kyoto Horikawagojo",events:[["08:30","京都飯店出發"],["09:00","東寺 弘法市"],["11:30","下鴨神社・糺之森"],["14:30","移動伏見稻荷"],["15:00","伏見稻荷大社"],["17:30","京都站晚餐"]]},
{date:"11/22",title:"勝尾寺・箕面・大阪",sub:"退房＋包車移動日",hotel:"Hearton Hotel Shinsaibashi Nagahoridori",events:[["08:00","京都飯店退房｜行李上車"],["09:30","勝尾寺"],["11:30","箕面公園・瀑布"],["13:30","橋本亭・柚子咖啡"],["14:45","杯麵博物館 池田"],["17:00","大阪飯店入住"]]},
{date:"11/23",title:"新世界 → 道頓堀 → 心齋橋",sub:"大阪街拍・美食・採買",hotel:"Hearton Hotel Shinsaibashi Nagahoridori",events:[["09:00","大阪飯店出發"],["09:30","新世界・通天閣"],["12:00","日本橋"],["13:00","難波・千日前"],["15:00","道頓堀"],["17:00","心齋橋・長堀橋"],["18:30","大阪晚餐"]]},
{date:"11/24",title:"大阪 → KIX → 台灣",sub:"回程・退稅・最後採買",hotel:"Hearton Hotel Shinsaibashi Nagahoridori",events:[["08:00","飯店早餐／最後整理"],["09:30","退房・8 人行李集合"],["10:00","包車 → KIX"],["11:00","KIX｜報到・退稅／海關・最後採買"],["14:00","JX823 → TPE"],["16:15","抵達 TPE"]]}
];
const food=[
["かつくら寺町店","DAY1","🟢 順路","👥 8人適性待確認"],["% ARABICA Higashiyama","DAY2","🟢 順路","☕ 休息候選"],["GOKAGO","DAY2","🟢 順路","🍡 小吃"],["天ぷら圓堂八坂本店","DAY2","🟡 建議預約","👥 8人需確認"],["出町ろろろ","DAY3","🟡 小繞路","🍴 正餐"],["祢ざめ家","DAY3","🟢 路線內","🍴 正餐"],["串かつてんぐ","DAY5","🟢 順路","🍴 正餐"],["551 HORAI","DAY5","🟢 順路","⚡ 快速"],["りくろーおじさん","DAY5","🟢 順路","🎁 外帶"]
];
const near=[["3COINS 京都寺町店","DAY1","🔥 3COINS 熱門推薦"],["LE LABO Kyoto Machiya","DAY1","🛍️ 購物"],["本家西尾八橋清水店","DAY2","🎁 伴手禮"],["TAPTAP Lab","DAY5","💍 Coin Ring"],["HISEKI","DAY5","💍 Coin Ring"],["新世界市場","DAY5","🏮 LOCAL"],["KIX 最後採買","DAY6","🎁 回程"]];
let day=+(localStorage.day||0),tab=localStorage.tab||"today",modal="";
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}function load(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}
function maps(q){window.open("https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(q),"_blank")}
function locate(){if(!navigator.geolocation)return alert("此瀏覽器不支援定位");navigator.geolocation.getCurrentPosition(p=>{save("loc",{lat:p.coords.latitude,lng:p.coords.longitude,time:Date.now()});render()},()=>alert("無法取得定位，請允許此網站使用位置"))}
function nextEvent(){let now=new Date(),cur=now.getHours()*60+now.getMinutes(),es=days[day].events;for(const e of es){let [h,m]=e[0].split(":").map(Number);if(h*60+m>=cur)return e}return es[es.length-1]}
function addExpense(){modal="expense";render()}function addPoi(){modal="poi";render()}function closeModal(){modal="";render()}
function submitExpense(){let a=load("expenses",[]);a.push({name:document.querySelector("#en").value||"共同支出",amount:+document.querySelector("#ea").value||0,payer:document.querySelector("#ep").value||"NOAH",day:day+1});save("expenses",a);closeModal()}
function submitPoi(){let a=load("candidates",[]);a.push({name:document.querySelector("#pn").value||"未命名候選",link:document.querySelector("#pl").value,day:day+1,votes:1});save("candidates",a);closeModal()}
function render(){localStorage.day=day;localStorage.tab=tab;let d=days[day];document.querySelector("#app").innerHTML='<div class="app"><header class="hero"><div class="eyebrow">KYOTO・OSAKA 2026</div><h1>京都・大阪 秋旅</h1><p>'+d.date+'｜'+d.title+'</p><p>'+d.sub+'</p><span class="badge">BETA｜8人攝影旅行</span></header><div class="days">'+days.map((x,i)=>'<button class="day '+(i==day?'active':'')+'" onclick="day='+i+';render()">D'+(i+1)+'</button>').join("")+'</div><main class="main">'+content(d)+'</main><nav class="nav">'+[["today","今日"],["photo","攝影"],["food","美食"],["near","周邊"]].map(x=>'<button class="'+(tab==x[0]?'active':'')+'" onclick="tab=\''+x[0]+'\';render()">'+x[1]+'</button>').join("")+'</nav></div>'+modalHtml()}
function content(d){if(tab==="today"){let n=nextEvent(),loc=load("loc",null),exp=load("expenses",[]);return '<div class="notice">攝影決定路線，美食提供選擇。｜目前資料・出發前再確認</div><div class="toolbar"><button class="action" onclick="locate()">📍 '+(loc?"重新定位":"取得位置")+'</button><button class="action" onclick="maps(\''+d.hotel+'\')">🏨 回飯店</button></div><section class="where"><h2>現在去哪？</h2><div class="big">🟢 '+n[1]+'</div><p class="muted">下一個固定/建議節點 '+n[0]+'。正式版將加入移動時間、營業時間與安全 buffer；無資料時不捏造 ETA。</p><div class="choices"><button class="choice" onclick="tab=\'photo\';render()">📸 拍照</button><button class="choice" onclick="tab=\'food\';render()">🍴 吃東西</button><button class="choice" onclick="maps(\'cafe near me\')">☕ 附近休息</button><button class="choice" onclick="maps(\''+d.hotel+'\')">🏨 回飯店</button></div></section><section class="card"><h2 class="section-title">旅行控制</h2><div class="mini-grid"><button class="mini" onclick="addExpense()">💴 旅費</button><button class="mini" onclick="alert(\'集合模式：BETA 下一輪加入 8 人到達狀態\')">👥 集合</button><button class="mini" onclick="addPoi()">＋想去</button><button class="mini" onclick="alert(\'Plan A 正常｜B 雨天｜C 疲累縮短\')">☔ A/B/C</button><button class="mini" onclick="alert(\'出發準備：護照/VJW/報到/eSIM 將加入完成矩陣\')">✈️ 準備</button><button class="mini" onclick="alert(\'119 救護消防｜110 警察\')">🆘 安全</button></div>'+(exp.length?'<p class="muted">本機已記 '+exp.length+' 筆共同支出</p>':'')+'</section><section class="card"><h2 class="section-title">DAY '+(day+1)+' 行程</h2><div class="timeline">'+d.events.map(e=>'<div class="event"><div class="time">'+e[0]+'</div><h3>'+e[1]+'</h3><div class="chips"><button class="action" onclick="maps(\''+e[1]+'\')">導航</button><span class="chip">順路優先</span></div></div>').join("")+'</div></section>'}
if(tab==="photo")return '<div class="notice">📸 攝影導覽｜依實際路線安排，不為理想光線硬改整天行程</div>'+d.events.filter((_,i)=>i>0).slice(0,4).map((e,i)=>'<div class="card poi"><div class="photo-placeholder">參考照片位置｜正式版補圖</div><h3>📸 '+e[1]+'</h3><div class="meta">建議時段 '+e[0]+'｜'+(i<2?"🟢 今日重點":"🟡 視進度")+'</div><p>R8：人像優先 RF45mm f/1.2；環境與狹窄街景使用 RF24–50。構圖以人物＋環境層次為主。</p><button class="action" onclick="maps(\''+e[1]+'\')">導航</button></div>').join("");
let arr=tab==="food"?food.filter(x=>x[1]==="DAY"+(day+1)):near.filter(x=>x[1]==="DAY"+(day+1));let cand=load("candidates",[]).filter(x=>x.day===day+1);return '<div class="toolbar"><button class="action" onclick="addPoi()">＋新增想去</button><button class="action" onclick="locate()">📍重新定位</button></div><div class="notice">'+(tab==="food"?"🍴 美食｜同路線多選，不跨區追店":"🛍️ 周邊｜購物・伴手禮・LOCAL・Coin Ring")+'</div>'+arr.map(p=>'<div class="card poi"><h3>'+p[0]+'</h3><div class="meta">'+p[1]+'｜目前資料・出發前再確認</div><p class="good">'+p[2]+'</p><p>'+p[3]+'</p><div class="chips"><button class="action" onclick="maps(\''+p[0]+'\')">導航</button><button class="action" onclick="alert(\'本機投票 +1\')">♡ +1</button></div></div>').join("")+cand.map(p=>'<div class="card"><h3>♡ '+p.name+'</h3><div class="meta">團員候選｜DAY'+p.day+'</div><button class="action" onclick="'+(p.link?"window.open(\'"+p.link+"\',\'_blank\')":"maps(\'"+p.name+"\')")+'">查看</button></div>').join("")}
function modalHtml(){if(!modal)return "";if(modal==="expense")return '<div class="modal" onclick="if(event.target===this)closeModal()"><div class="modalbox"><h2>💴 記一筆共同旅費</h2><label>項目</label><input id="en" placeholder="例如：晚餐"><label>總額 JPY</label><input id="ea" type="number" inputmode="numeric" placeholder="8000"><label>付款人</label><input id="ep" value="NOAH"><p class="muted">BETA 預設 8 人均分；正式版支援 2–8 人與自訂分攤。</p><div class="row"><button class="action" onclick="submitExpense()">儲存</button><button class="action" onclick="closeModal()">取消</button></div></div></div>';return '<div class="modal" onclick="if(event.target===this)closeModal()"><div class="modalbox"><h2>＋新增想去</h2><label>店家／景點名稱</label><input id="pn" placeholder="例如：某某咖啡"><label>Google Maps 連結（可留空）</label><input id="pl" placeholder="https://maps.app.goo.gl/..."><p class="muted">先進候選池，不會自動改正式行程。</p><div class="row"><button class="action" onclick="submitPoi()">加入 DAY'+(day+1)+'</button><button class="action" onclick="closeModal()">取消</button></div></div></div>'}
render();