const D=[
{date:"11/19",dow:"四",title:"台灣 → 關西 → 京都",sub:"抵達京都・晚上自由活動",hotel:"Comfort Hotel Kyoto Horikawagojo",fixed:false,e:[["03:40","NOAH 新竹市出發","fixed"],["04:00","1250 客運 → 桃園機場 T1","fixed"],["05:00","T1 全員集合","fixed"],["07:40","JX820 → KIX","fixed"],["11:10","抵達 KIX","fixed"],["12:30","包車 → 京都飯店","fixed"],["15:00","飯店寄放／入住・休息","fixed"],["16:00","寺町・新京極・四条河原町","flex"],["18:30","沿途晚餐","flex"]]},
{date:"11/20",dow:"五",title:"和服・清水寺・祇園",sub:"本次主要人像攝影日",hotel:"Comfort Hotel Kyoto Horikawagojo",fixed:false,e:[["09:00","和服店｜3位女生著裝・髮型","fixed"],["10:00","清水寺","flex"],["11:15","三年坂・二年坂","flex"],["12:30","沿途午餐","flex"],["14:00","八坂塔・高台寺方向","flex"],["16:00","祇園・花見小路","flex"],["17:15","歸還和服 → 河原町晚餐","fixed"]]},
{date:"11/21",dow:"六",title:"弘法市・糺之森・伏見稻荷",sub:"包車固定行程",hotel:"Comfort Hotel Kyoto Horikawagojo",fixed:true,e:[["08:30","京都飯店出發","fixed"],["09:00","東寺 弘法市","fixed"],["11:30","下鴨神社・糺之森","fixed"],["14:30","移動伏見稻荷","fixed"],["15:00","伏見稻荷大社","fixed"],["17:30","京都站晚餐","flex"]]},
{date:"11/22",dow:"日",title:"勝尾寺・箕面・大阪",sub:"退房＋包車移動日",hotel:"Hearton Hotel Shinsaibashi Nagahoridori",fixed:true,e:[["08:00","京都飯店退房｜行李上車","fixed"],["09:30","勝尾寺","fixed"],["11:30","箕面公園・瀑布","fixed"],["13:30","橋本亭・柚子咖啡","fixed"],["14:45","杯麵博物館 池田","fixed"],["17:00","大阪飯店入住","fixed"]]},
{date:"11/23",dow:"一",title:"新世界 → 道頓堀 → 心齋橋",sub:"大阪街拍・美食・採買",hotel:"Hearton Hotel Shinsaibashi Nagahoridori",fixed:false,e:[["09:00","大阪飯店出發","fixed"],["09:30","新世界・通天閣","flex"],["12:00","日本橋","flex"],["13:00","難波・千日前","flex"],["15:00","道頓堀","flex"],["17:00","心齋橋・長堀橋","flex"],["18:30","大阪晚餐","flex"]]},
{date:"11/24",dow:"二",title:"大阪 → KIX → 台灣",sub:"回程・退稅・最後採買",hotel:"Hearton Hotel Shinsaibashi Nagahoridori",fixed:true,e:[["08:00","飯店早餐／最後整理","flex"],["09:30","退房・8 人行李集合","fixed"],["10:00","包車 → KIX","fixed"],["11:00","KIX｜報到・退稅／海關・最後採買","fixed"],["14:00","JX823 → TPE","fixed"],["16:15","抵達 TPE","fixed"]]}];
const FOOD=[["1","かつくら寺町店","DAY1","🟢 順路","👥 8人適性待確認"],["2","% ARABICA Higashiyama","DAY2","🟢 順路","☕ 15–30 分"],["3","GOKAGO","DAY2","🟢 順路","🍡 15–30 分"],["4","天ぷら圓堂八坂本店","DAY2","🟡 建議預約","👥 8人需確認"],["5","出町ろろろ","DAY3","🟡 小繞路","🍴 45–60 分"],["6","祢ざめ家","DAY3","🟢 路線內","🍴 45–60 分"],["7","串かつてんぐ","DAY5","🟢 順路","🍴 45–60 分"],["8","551 HORAI","DAY5","🟢 順路","⚡ 15–30 分"],["9","りくろーおじさん","DAY5","🟢 順路","🎁 外帶"]];
const NEAR=[["a","3COINS 京都寺町店","DAY1","🔥 3COINS 熱門推薦"],["b","LE LABO Kyoto Machiya","DAY1","🛍️ 購物"],["c","本家西尾八橋清水店","DAY2","🎁 伴手禮"],["d","TAPTAP Lab","DAY5","💍 Coin Ring"],["e","HISEKI","DAY5","💍 Coin Ring"],["f","新世界市場","DAY5","🏮 LOCAL"],["g","KIX 最後採買","DAY6","🎁 回程"]];
let day=+(localStorage.getItem("day")||0),tab=localStorage.getItem("tab")||"today",sheet="";
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function maps(q){open("https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(q),"_blank")}
function locate(){navigator.geolocation?.getCurrentPosition(p=>{set("loc",{lat:p.coords.latitude,lng:p.coords.longitude,at:new Date().toISOString()});render()},()=>alert("無法取得定位。請允許瀏覽器位置權限。"),{enableHighAccuracy:true,timeout:10000})}
function nowNode(){const d=D[day],n=new Date(),cur=n.getHours()*60+n.getMinutes();for(const x of d.e){let [h,m]=x[0].split(":").map(Number);if(h*60+m>=cur)return x}return d.e.at(-1)}
function vote(id){let v=get("votes",{});v[id]=(v[id]||0)+1;set("votes",v);render()}
function plan(p){set("plan"+day,p);render()}
function addExpense(){sheet="expense";render()}function addPoi(){sheet="poi";render()}function expenses(){sheet="expenses";render()}
function saveExpense(){let a=get("expenses",[]);a.push({name:q("#en").value||"共同支出",amount:+q("#ea").value||0,payer:q("#ep").value||"NOAH",people:+q("#ec").value||8,day:day+1});set("expenses",a);sheet="expenses";render()}
function savePoi(){let a=get("candidates",[]);a.push({name:q("#pn").value||"未命名候選",link:q("#pl").value,day:day+1,votes:1});set("candidates",a);sheet="";render()}
function q(s){return document.querySelector(s)}function closeSheet(){sheet="";render()}
function render(){localStorage.setItem("day",day);localStorage.setItem("tab",tab);let d=D[day];q("#app").innerHTML='<div class="app"><header class="hero"><div class="eyebrow">KYOTO • OSAKA 2026</div><h1>京都・大阪 秋旅</h1><div class="date">'+d.date+'（'+d.dow+'）｜'+d.title+'</div><div class="sub">'+d.sub+'</div><span class="badge">BETA｜8人攝影旅行</span></header><div class="days">'+D.map((x,i)=>'<button class="day '+(i===day?"active":"")+'" onclick="day='+i+';render()"><b>D'+(i+1)+'</b><small>'+x.date+'</small></button>').join("")+'</div><main class="main">'+page(d)+'</main><nav class="nav">'+[["today","⌂","今日"],["photo","◉","攝影"],["food","♨","美食"],["near","⌖","周邊"]].map(x=>'<button class="'+(tab===x[0]?"active":"")+'" onclick="tab=\''+x[0]+'\';render()"><i>'+x[1]+'</i>'+x[2]+'</button>').join("")+'</nav></div>'+sheetHtml()}
function page(d){if(tab==="today"){let n=nowNode(),loc=get("loc",null),p=get("plan"+day,"A"),ex=get("expenses",[]);return '<div class="notice">攝影決定路線，美食提供選擇。｜目前資料・出發前再確認</div><div class="top-actions"><button class="btn" onclick="locate()">📍 '+(loc?"重新定位":"取得位置")+'</button><button class="btn" onclick="maps(\''+d.hotel+'\')">🏨 回飯店</button></div><section class="decision"><div class="label">NOW｜現在去哪？</div><h2>🟢 '+n[1]+'</h2><div class="statusline"><span class="pill">下一節點 '+n[0]+'</span><span class="pill">'+(d.fixed?"固定移動日":"可彈性調整")+'</span><span class="pill">Plan '+p+'</span></div><div class="why">依目前時間與今日剩餘節點重新建議。即時交通 ETA／營業資訊尚未接資料源時會明確標示待確認，不產生假數字。</div><div class="quick"><button onclick="tab=\'photo\';render()">📸<br>拍照</button><button onclick="tab=\'food\';render()">🍴<br>吃東西</button><button onclick="maps(\'cafe near me\')">☕<br>休息</button><button onclick="maps(\''+d.hotel+'\')">🏨<br>飯店</button></div></section><section class="card"><div class="section-head"><h2>旅行控制</h2><span>實際可操作 BETA</span></div><div class="control-grid"><button onclick="addExpense()">💴<br>記旅費</button><button onclick="expenses()">🧾<br>共同帳本</button><button onclick="addPoi()">＋<br>新增想去</button><button onclick="plan(\''+(p==="A"?"B":p==="B"?"C":"A")+'\')">☔<br>Plan '+p+'</button><button onclick="alert(\'集合模式下一輪：8 人到達狀態＋5/8 顯示\')">👥<br>集合</button><button onclick="alert(\'出發準備下一輪加入 8 人完成矩陣\')">✈️<br>出發準備</button></div><div class="empty">本機已保存 '+ex.length+' 筆旅費；正式 Floot 版改為 8 人同步資料庫。</div></section><section class="card"><div class="section-head"><h2>DAY '+(day+1)+' 行程</h2><span>●固定　●彈性</span></div><div class="timeline">'+d.e.map(x=>'<div class="event '+(x[2]==="flex"?"flex":"")+'"><div class="time">'+x[0]+'</div><h3>'+x[1]+'</h3><div class="meta">'+(x[2]==="fixed"?"固定／交通節點":"彈性停留・依現場調整")+'</div><div class="chips"><button class="linkbtn" onclick="maps(\''+x[1]+'\')">Google Maps</button><span class="chip">'+(x[2]==="fixed"?"🔒 固定":"↔ 可調整")+'</span></div></div>').join("")+'</div></section>'}
if(tab==="photo")return '<div class="notice">📸 攝影導覽｜依實際路線安排，不為理想光線硬改整天行程</div>'+d.e.filter((_,i)=>i>0).slice(0,5).map((x,i)=>'<article class="card poi"><div class="photo">PHOTO GUIDE · DAY '+(day+1)+'</div><h3>'+x[1]+'</h3><div class="meta">建議 '+x[0]+' 前後｜'+(i<2?"🟢 今日重點":"🟡 視進度")+'</div><p>Canon R8｜人像優先 RF45mm f/1.2；環境與狹窄街景改 RF24–50。構圖以人物＋環境層次為主。</p><button class="btn" onclick="maps(\''+x[1]+'\')">開啟導航</button></article>').join("");
let arr=(tab==="food"?FOOD:NEAR).filter(x=>x[2]==="DAY"+(day+1)),v=get("votes",{}),cand=get("candidates",[]).filter(x=>x.day===day+1);return '<div class="top-actions"><button class="btn dark" onclick="addPoi()">＋ 新增想去</button><button class="btn" onclick="locate()">📍 重新定位</button></div><div class="notice">'+(tab==="food"?"🍴 美食｜路線優先，不跨區追店":"🛍️ 周邊｜購物・伴手禮・LOCAL・Coin Ring")+'</div>'+arr.map(x=>'<article class="card poi"><h3>'+x[1]+'</h3><div class="meta">'+x[2]+'｜目前資料・出發前再確認</div><p class="'+(x[3].includes("🟢")?"route-good":"route-warn")+'">'+x[3]+'</p><p>'+x[4]+'</p><div class="chips"><button class="linkbtn" onclick="maps(\''+x[1]+'\')">導航</button><button class="linkbtn" onclick="vote(\''+x[0]+'\')">♡ '+(v[x[0]]||0)+'</button></div></article>').join("")+(arr.length?"":'<div class="card empty">今日目前沒有已鎖定的'+(tab==="food"?"美食":"周邊")+'候選。</div>')+cand.map(x=>'<article class="card"><h3>♡ '+x.name+'</h3><div class="meta">團員候選池｜DAY'+x.day+'｜不自動更改正式行程</div><button class="btn" onclick="'+(x.link?"open(\'"+x.link+"\',\'_blank\')":"maps(\'"+x.name+"\')")+'">查看</button></article>').join("")}
function sheetHtml(){if(!sheet)return "";if(sheet==="expense")return '<div class="modal" onclick="if(event.target===this)closeSheet()"><div class="sheet"><h2>💴 記一筆共同旅費</h2><label>項目</label><input id="en" placeholder="例如：DAY2 晚餐"><label>總額 JPY</label><input id="ea" type="number" inputmode="numeric"><label>付款人</label><input id="ep" value="NOAH"><label>參與人數</label><select id="ec">'+[2,3,4,5,6,7,8].map(n=>'<option '+(n===8?"selected":"")+'>'+n+'</option>').join("")+'</select><div class="chips"><button class="btn green" onclick="saveExpense()">儲存</button><button class="btn" onclick="closeSheet()">取消</button></div></div></div>';if(sheet==="expenses"){let a=get("expenses",[]),total=a.reduce((s,x)=>s+x.amount,0);return '<div class="modal" onclick="if(event.target===this)closeSheet()"><div class="sheet"><h2>🧾 共同帳本</h2><p><b>目前總支出 ¥'+total.toLocaleString()+'</b></p>'+(a.length?a.map(x=>'<div class="expense"><span>D'+x.day+' '+x.name+'<br><small>'+x.payer+' 付款・'+x.people+'人</small></span><b>¥'+x.amount.toLocaleString()+'</b></div>').join(""):'<div class="empty">尚未新增旅費。</div>')+'<br><button class="btn" onclick="closeSheet()">關閉</button></div></div>'}return '<div class="modal" onclick="if(event.target===this)closeSheet()"><div class="sheet"><h2>＋ 新增想去</h2><label>店家／景點名稱</label><input id="pn" placeholder="輸入名稱"><label>Google Maps 連結</label><input id="pl" placeholder="https://maps.app.goo.gl/..."><p class="meta">先加入 DAY'+(day+1)+' 候選池，不會自動修改正式行程。</p><div class="chips"><button class="btn green" onclick="savePoi()">加入候選</button><button class="btn" onclick="closeSheet()">取消</button></div></div></div>'}
render();