const D=[
{date:"11/19",title:"台灣 → 關西 → 京都",sub:"出發・抵達京都・晚上自由活動",hotel:"Comfort Hotel Kyoto Horikawagojo",e:[["03:40","NOAH 新竹市出發","f"],["04:00","1250 客運 → 桃園機場 T1","f"],["05:00","T1 全員集合","f"],["07:40","JX820 → KIX","f"],["11:10","抵達 KIX","f"],["12:30","包車 → 京都飯店","f"],["15:00","飯店寄放／入住・休息","f"],["16:00","寺町・新京極・四条河原町","x"],["18:30","沿途晚餐","x"]]},
{date:"11/20",title:"和服・清水寺・祇園",sub:"主要人像攝影日",hotel:"Comfort Hotel Kyoto Horikawagojo",e:[["09:00","和服店｜3位女生著裝・髮型","f"],["10:00","清水寺","x"],["11:15","三年坂・二年坂","x"],["12:30","沿途午餐","x"],["14:00","八坂塔・高台寺方向","x"],["16:00","祇園・花見小路","x"],["17:15","歸還和服 → 河原町晚餐","f"]]},
{date:"11/21",title:"弘法市・糺之森・伏見稻荷",sub:"包車固定行程",hotel:"Comfort Hotel Kyoto Horikawagojo",e:[["08:30","京都飯店出發","f"],["09:00","東寺 弘法市","f"],["11:30","下鴨神社・糺之森","f"],["14:30","移動伏見稻荷","f"],["15:00","伏見稻荷大社","f"],["17:30","京都站晚餐","x"]]},
{date:"11/22",title:"勝尾寺・箕面・大阪",sub:"退房＋包車移動日",hotel:"Hearton Hotel Shinsaibashi Nagahoridori",e:[["08:00","京都飯店退房｜行李上車","f"],["09:30","勝尾寺","f"],["11:30","箕面公園・瀑布","f"],["13:30","橋本亭・柚子咖啡","f"],["14:45","杯麵博物館 池田","f"],["17:00","大阪飯店入住","f"]]},
{date:"11/23",title:"新世界 → 道頓堀 → 心齋橋",sub:"大阪街拍・美食・採買",hotel:"Hearton Hotel Shinsaibashi Nagahoridori",e:[["09:00","大阪飯店出發","f"],["09:30","新世界・通天閣","x"],["12:00","日本橋","x"],["13:00","難波・千日前","x"],["15:00","道頓堀","x"],["17:00","心齋橋・長堀橋","x"],["18:30","大阪晚餐","x"]]},
{date:"11/24",title:"大阪 → KIX → 台灣",sub:"回程・退稅・最後採買",hotel:"Hearton Hotel Shinsaibashi Nagahoridori",e:[["08:00","飯店早餐／最後整理","x"],["09:30","退房・8 人行李集合","f"],["10:00","包車 → KIX","f"],["11:00","KIX｜報到・退稅／海關・最後採買","f"],["14:00","JX823 → TPE","f"],["16:15","抵達 TPE","f"]]}];
const FOOD={0:["かつくら寺町店"],1:["% ARABICA Higashiyama","GOKAGO","天ぷら圓堂八坂本店"],2:["出町ろろろ","祢ざめ家"],4:["串かつてんぐ","551 HORAI","りくろーおじさん"]};
const NEAR={0:["3COINS 京都寺町店","LE LABO Kyoto Machiya"],1:["本家西尾八橋清水店"],4:["TAPTAP Lab","HISEKI","新世界市場"],5:["KIX 最後採買"]};
let day=+(localStorage.day||0),tab=localStorage.tab||"today",sheet="";
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),q=s=>document.querySelector(s);
function maps(x){open("https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(x),"_blank")}
function locate(){navigator.geolocation?.getCurrentPosition(p=>{set("loc",{lat:p.coords.latitude,lng:p.coords.longitude});render()},()=>alert("請允許瀏覽器使用位置"))}
function next(){let c=new Date().getHours()*60+new Date().getMinutes();return D[day].e.find(x=>{let a=x[0].split(":").map(Number);return a[0]*60+a[1]>=c})||D[day].e.at(-1)}
function render(){localStorage.day=day;localStorage.tab=tab;let d=D[day];q("#app").innerHTML='<div class="app"><header class="hero"><div class="hero-top"><span>京都・大阪 秋旅</span><span class="beta">2026 BETA</span></div><div class="kicker">DAY '+(day+1)+' · '+d.date+'</div><h1>'+d.title+'</h1><div class="sub">'+d.sub+'</div></header><section class="tripmeta"><div class="meta-row"><span>2026.11.19 — 11.24</span><span>8人攝影旅行</span></div><div class="motto">攝影決定路線，美食提供選擇。</div><div class="days">'+D.map((x,i)=>'<button class="day '+(i===day?"active":"")+'" onclick="day='+i+';render()"><b>'+(i+1)+'</b><small>'+x.date+'</small></button>').join("")+'</div></section><main class="main">'+page(d)+'</main><nav class="nav">'+[["today","⌾","今日"],["photo","▣","攝影"],["food","♜","美食"],["near","▤","周邊"]].map(x=>'<button class="'+(tab===x[0]?"active":"")+'" onclick="tab=\''+x[0]+'\';render()"><i>'+x[1]+'</i>'+x[2]+'</button>').join("")+'</nav></div>'+modal()}
function page(d){if(tab==="today"){let n=next(),loc=get("loc",null),p=get("plan"+day,"A");return '<div class="section-kicker">TODAY\'S ROUTE</div><div class="section-title">今日行程</div><div class="route-note"><span>小提醒｜'+(day===5?"09:30 退房・10:00 包車":"依現場節奏彈性調整")+'</span><span class="count">● '+d.e.length+'行程</span></div><section class="timeline-card">'+d.e.map((x,i)=>'<div class="event '+(x[2]==="x"?"flex":"")+'"><span class="num">'+String(i+1).padStart(2,"0")+'</span><span class="time">'+x[0]+'</span><span class="event-title">'+x[1]+'</span></div>').join("")+'</section><div class="actions"><button class="action primary" onclick="locate()">📍 '+(loc?"重新定位":"取得位置")+'</button><button class="action" onclick="maps(\''+d.hotel+'\')">回飯店</button></div><section class="decision"><div class="decision-head"><div><div class="section-kicker">RIGHT NOW</div><h3>現在去哪？</h3></div><span class="chip">Plan '+p+'</span></div><p><b>🟢 '+n[1]+'</b>｜下一節點 '+n[0]+'。尚未接即時交通資料時不顯示假 ETA。</p><div class="chips"><button class="action" onclick="maps(\''+n[1]+'\')">導航</button><button class="action" onclick="tab=\'food\';render()">吃東西</button><button class="action" onclick="tab=\'photo\';render()">拍照</button></div><div class="grid"><button onclick="sheet=\'expense\';render()">💴 旅費</button><button onclick="sheet=\'poi\';render()">＋ 想去</button><button onclick="set(\'plan'+day,p===\'A\'?\'B\':p===\'B\'?\'C\':\'A\');render()">☔ A/B/C</button></div></section>'}
if(tab==="photo")return '<div class="section-kicker">PHOTO GUIDE</div><div class="section-title">今日攝影</div>'+d.e.slice(1,5).map(x=>'<article class="card"><div class="photo"></div><h3>'+x[1]+'</h3><div class="small">建議 '+x[0]+' 前後｜Canon R8｜RF45mm f/1.2 人像優先；環境街景改 RF24–50。</div><div class="actions"><button class="action" onclick="maps(\''+x[1]+'\')">導航</button></div></article>').join("");
let arr=(tab==="food"?FOOD[day]:NEAR[day])||[],cand=get("candidates",[]).filter(x=>x.day===day+1);return '<div class="section-kicker">'+(tab==="food"?"FOOD OPTIONS":"AROUND YOU")+'</div><div class="section-title">'+(tab==="food"?"沿途美食":"順路周邊")+'</div><div class="actions"><button class="action primary" onclick="sheet=\'poi\';render()">＋新增想去</button><button class="action" onclick="locate()">重新定位</button></div>'+arr.map(x=>'<article class="card"><h3>'+x+'</h3><div class="small">DAY'+(day+1)+'｜目前資料・出發前再確認｜路線適性待實測</div><div class="actions"><button class="action" onclick="maps(\''+x+'\')">導航</button><button class="action" onclick="alert(\'已記錄 +1\')">♡ +1</button></div></article>').join("")+cand.map(x=>'<article class="card"><h3>♡ '+x.name+'</h3><div class="small">團員候選池｜不自動修改正式行程</div></article>').join("")}
function modal(){if(!sheet)return"";if(sheet==="expense")return '<div class="modal" onclick="if(event.target===this){sheet=\'\';render()}"><div class="sheet"><h2>記一筆共同旅費</h2><input id="en" placeholder="項目"><input id="ea" type="number" placeholder="總額 JPY"><input id="ep" value="NOAH"><select id="ec">'+[2,3,4,5,6,7,8].map(n=>'<option '+(n===8?"selected":"")+'>'+n+'</option>').join("")+'</select><button class="action primary" onclick="let a=get(\'expenses\',[]);a.push({name:q(\'#en\').value,amount:+q(\'#ea\').value,payer:q(\'#ep\').value,people:+q(\'#ec\').value});set(\'expenses\',a);sheet=\'\';render()">儲存</button></div></div>';return '<div class="modal" onclick="if(event.target===this){sheet=\'\';render()}"><div class="sheet"><h2>新增想去</h2><input id="pn" placeholder="店家／景點名稱"><input id="pl" placeholder="Google Maps 連結"><button class="action primary" onclick="let a=get(\'candidates\',[]);a.push({name:q(\'#pn\').value||\'未命名\',link:q(\'#pl\').value,day:day+1});set(\'candidates\',a);sheet=\'\';render()">加入 DAY'+(day+1)+' 候選</button></div></div>'}
render();