const OWNER="mask073110",REPO="kyoto-osaka-2026-beta",PATH="data/shopping.json";
function cors(req,res){const o=req.headers.origin||"";if(["https://mask073110.github.io","https://kyoto-osaka-2026-beta.vercel.app"].includes(o))res.setHeader("Access-Control-Allow-Origin",o);res.setHeader("Vary","Origin");res.setHeader("Access-Control-Allow-Methods","GET,POST,OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type")}
async function gh(path,opts={}){const token=process.env.GITHUB_TOKEN;if(!token)throw new Error("Vercel 尚未設定 GITHUB_TOKEN");return fetch("https://api.github.com/repos/"+OWNER+"/"+REPO+"/contents/"+path,{...opts,headers:{"Accept":"application/vnd.github+json","Authorization":"Bearer "+token,"X-GitHub-Api-Version":"2022-11-28","Content-Type":"application/json",...(opts.headers||{})}})}
async function read(){const r=await gh(PATH+"?ts="+Date.now());if(r.status===404)return {items:[],sha:null};const d=await r.json();if(!r.ok)throw new Error(d.message||"GitHub read failed");let txt=Buffer.from((d.content||"").replace(/\n/g,""),"base64").toString("utf8");let j=JSON.parse(txt||'{"items":[]}');return {items:Array.isArray(j.items)?j.items:[],sha:d.sha}}
function cleanItem(x){if(!x||typeof x!=="object")return null;const id=String(x.id||"").slice(0,100);if(!id)return null;return {...x,id,name:String(x.name||"待買商品").slice(0,300),note:String(x.note||"").slice(0,1000),likes:Array.isArray(x.likes)?x.likes.slice(0,20).map(v=>String(v).slice(0,60)):[],comments:Array.isArray(x.comments)?x.comments.slice(-100).map(v=>({user:String(v?.user||"團員").slice(0,60),text:String(v?.text||"").slice(0,120),time:String(v?.time||"").slice(0,40)})):[]}}
function apply(items,body){const op=body?.op;
 if(op==="add"){const item=cleanItem(body.item);if(!item)throw new Error("商品資料格式錯誤");if(items.some(x=>x.id===item.id))return items;return [...items,item]}
 const id=String(body?.id||"");const i=items.findIndex(x=>x.id===id);if(i<0){if(op==="delete")return items;throw new Error("找不到商品，請重新整理")}
 if(op==="delete")return items.filter(x=>x.id!==id);
 if(op==="toggleDone"){let out=items.slice();out[i]={...out[i],done:!out[i].done};return out}
 if(op==="setDone"){let out=items.slice();out[i]={...out[i],done:!!body.done};return out}
 if(op==="toggleWant"){const user=String(body?.user||"").slice(0,60);if(!user)throw new Error("使用者資料錯誤");let likes=Array.isArray(items[i].likes)?items[i].likes.slice():[],p=likes.indexOf(user);if(p>=0)likes.splice(p,1);else likes.push(user);let out=items.slice();out[i]={...out[i],likes};return out}
 if(op==="comment"){const user=String(body?.user||"團員").slice(0,60),msg=String(body?.text||"").trim().slice(0,120);if(!msg)throw new Error("留言不可空白");let comments=Array.isArray(items[i].comments)?items[i].comments.slice():[];comments.push({user,text:msg,time:new Date().toISOString()});comments=comments.slice(-100);let out=items.slice();out[i]={...out[i],comments};return out}
 throw new Error("不支援的待買清單操作")
}
async function writeOperation(body){for(let attempt=0;attempt<4;attempt++){let cur=await read(),items=apply(cur.items,body);if(items.length>500)throw new Error("待買清單已達上限");let payload={message:"Shopping "+String(body.op||"update")+" "+String(body.id||body.item?.id||""),content:Buffer.from(JSON.stringify({items,updatedAt:new Date().toISOString()},null,2)).toString("base64"),branch:"main"};if(cur.sha)payload.sha=cur.sha;let r=await gh(PATH,{method:"PUT",body:JSON.stringify(payload)}),d=await r.json();if(r.ok)return items;if(r.status===409||r.status===422)continue;throw new Error(d.message||"GitHub write failed")}throw new Error("多人同時更新衝突，請再試一次")}
export default async function handler(req,res){cors(req,res);if(req.method==="OPTIONS")return res.status(204).end();try{if(req.method==="GET"){let d=await read();return res.status(200).json({items:d.items})}if(req.method!=="POST")return res.status(405).json({error:"方法不允許"});let body=typeof req.body==="string"?JSON.parse(req.body):req.body;if(body?.op){let items=await writeOperation(body);return res.status(200).json({ok:true,items})}let items=body?.items;if(!Array.isArray(items)||items.length>500)return res.status(400).json({error:"待買清單格式錯誤"});let cur=await read(),payload={message:"Update shared shopping list",content:Buffer.from(JSON.stringify({items,updatedAt:new Date().toISOString()},null,2)).toString("base64"),branch:"main"};if(cur.sha)payload.sha=cur.sha;let r=await gh(PATH,{method:"PUT",body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)return res.status(r.status).json({error:d.message||"GitHub write failed"});return res.status(200).json({ok:true,items})}catch(e){console.error(e);return res.status(500).json({error:e?.message||"Shopping sync failed"})}}
